name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request: :
    branches: [ main ]

env:
  UBUNTU_VERSION: ${{ env.UBUNTU_VERSION }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-test:
    runs-on: ${{ env.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17 SDK
        uses: action/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  docker-build-and-push:
    needs: build-and-test
    runs-on: ${{ env.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}
          platforms: linux/amd64, linux/arm64
  deploy:
    needs: docker-build-push
    runs-on: ${{ env.UBUNTU_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version
      - name: Run docker compose
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          docker compose up -d --build
          docker ps